name: CI

on:
  push:
    paths-ignore:
      - 'bench/**'
      - '*.md'
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'bench/**'
      - '*.md'
    branches:
      - master

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [8, 10, 12, 18, 20, 22]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: npm install

    - name: Test
      if: matrix.nodejs < 18
      run: npm test

    - name: Test w/ Coverage
      if: matrix.nodejs >= 18
      run: |
        npm install -g c8
        c8 --include=src npm test

    - name: Report
      if: matrix.nodejs >= 18
      run: |
        c8 report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
